/controller_node:
  ros__parameters:
    # backend_class Choices:
    #     controller.lqr_algorithm:LQRController
    #     controller.cbf_algorithm:CBFController
    #     controller.hj_algorithm:HJController
    backend_class: controller.lqr_algorithm:LQRController
    pose_topic: /robot_pose
    cmd_vel_topic: /cmd_vel
    control_rate: 5.0
    dt: 0.2

    # LQR
    lqr.horizon: 20
    lqr.x_cost: 5.0
    lqr.y_cost: 5.0
    lqr.theta_cost: 1.0
    lqr.v_cost: 0.1
    lqr.w_cost: 0.1
    lqr.v_min: -0.2
    lqr.v_max: 1.0
    lqr.w_min: -1.2
    lqr.w_max: 1.2

    # CBF
    cbf.gamma_cbf: 2.0
    cbf.lookahead_distance: 0.5
    cbf.center_margin_buffer: 0.05
    cbf.v_min: 0.0
    cbf.v_max: 1.0
    cbf.omega_max: 1.2 # omega for turn rate since w is used already
    cbf.w_cbf_v: 1.0
    cbf.w_cbf_omega: 0.05

    cbf.obstacle.center: [-0.5, 3.6]
    cbf.obstacle.radius: 0.35
    cbf.obstacle.safety_margin: 0.10

    # HJ least restrictive switching filter
    hj.epsilon: 0.1
    # IMPORTANT: if any of this number change, you need to modify accordingly and re-run the
    # HJ pre-computation script to generate new value function tables
    hj.obstacle.center: [-0.5, 3.6]
    hj.obstacle.radius: 0.35
    hj.obstacle.safety_margin: 0.10

    # FOR DEBUGGING ONLY: 
    # reference.kind: to_goal | straight | s_curve (see lqr/reference_trajectory.py) | path
    reference.kind: path
    reference.n_steps: 250
    goal_x: 3.5
    goal_y: 2.5
    goal_theta: 0.0